# Ansible playbook for configuring gnome

- hosts: all 
  connection: local
  tasks:
    - name: Save username
      shell: whoami
      register: username
    - name: hint for possible fingerprint sensors
      debug: 
        # Ansible does not support Multi Factor Auth and does not plan to do so
        # https://blog.guillaumea.fr/draft/ansible_fingerprint_reader/
        msg: "Remember to authenticate with fingerprint when gathering facts if you have a sensor on this device."


- hosts: all
  become: true
  tasks:
    - name: install stow
      dnf:
        name: 
          - stow 
          - gnome-tweaks
    - name: prepare directories for stowing files
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
      loop:
        - "/home/{{username.stdout}}/.themes"
        - "/home/{{username.stdout}}/.local/share/icons"
    - name: stow gnome files
      shell: |
        cd /home/{{ username.stdout }}/dotfiles
        stow gnome --dotfiles --verbose=2
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
    - name: set nordic themes with dconf
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: /org/gnome/shell/extensions/user-theme/name, value: "'Nordic-v40'"}
        - {key: /org/gnome/desktop/interface/clock-format, value: "'24h'"}
        - {key: /org/gnome/desktop/interface/cursor-theme, value: "'Nordzy-cursors'"}
        - {key: /org/gnome/desktop/interface/gtk-theme, value: "'Nordic-v40'"}
        - {key: /org/gnome/desktop/interface/icon-theme, value: "'Nordic-Folders'"}
    # - name: link dotfiles
    # - name: install packages
    # - name: configure gnome
