# Ansible playbook for configuring hyprland

- hosts: all 
  connection: local
  tasks:
    - name: Save username
      shell: whoami
      register: username
    - name: hint for possible fingerprint sensors
      debug: 
        # Ansible does not support Multi Factor Auth and does not plan to do so
        # https://blog.guillaumea.fr/draft/ansible_fingerprint_reader/
        msg: "Remember to authenticate with fingerprint when gathering facts if you have a sensor on this device."


- hosts: all
  become: true
  tasks:
    - name: install packages
      dnf:
        name: 
          - stow
          - hyprland
          - kitty
          - waybar
          - hyprpaper
    - name: stow files
      shell: |
        cd /home/{{ username.stdout }}/dotfiles
        stow hyprland waybar --dotfiles --verbose=2
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
    - name: Changing permissions of stowed scripts, adding "+x"
      file: dest={{ item }} mode=a+x
      loop:
         - /home/{{ username.stdout }}/bin/reload_hyprland_waybar.sh

